version: "3.8"
services:
    web:
        build: .
        ports:
            - "10088:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "10089:1433"
        environment:
            SA_PASSWORD: "Password789"
            ACCEPT_EULA: "Y"