version: "3.8"
services:
    web:
        build: .
        image: hlvtrinh/sample-data-grid
        ports:
            - "8080:80"
        depends_on:
            sample-db:
                condition: service_healthy

    sample-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password789
        ports:
            - "1433:1433"
        volumes:
            - mssql:/var/opt/mssql
        healthcheck:
            test: ["CMD-SHELL", '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password789 -Q "SELECT 1" || exit 1']
            interval: 10s
            timeout: 5s
            retries: 5

    db-importer:
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
            - mssql:/var/opt/mssql
            - ./.dbimporter:/dbimporter
        command: /dbimporter/importdb.sh
        depends_on:
            sample-db:
                condition: service_healthy
        

volumes:
    mssql:
